### ISSUE TITLE
Cant Upload File without catchError

### ISSUE THREAD

**Issue by conall1995** [BlueChilli/flutter_uploader#82]
i am trying to upload an image file 
its work fine in some of devices but not all 
some device like android v 4.4.4 and ...
`Start uploading for up
I/dalvikvm(20584): Rejecting re-init on previously-failed class Lokhttp3/internal/platform/Platform; v=0x0
E/WM-WorkerWrapper(20584): Work [ id=6bbb38d3-f97a-4f61-8170-d522d6ddca42, tags={ com.bluechilli.flutteruploader.UploadWorker, flutter_upload_task } ] failed because it threw an exception/error
E/WM-WorkerWrapper(20584): java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: okhttp3/internal/platform/Platform
E/WM-WorkerWrapper(20584): 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
E/WM-WorkerWrapper(20584): 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
E/WM-WorkerWrapper(20584): 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:284)
E/WM-WorkerWrapper(20584): 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
E/WM-WorkerWrapper(20584): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/WM-WorkerWrapper(20584): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/WM-WorkerWrapper(20584): 	at java.lang.Thread.run(Thread.java:841)
E/WM-WorkerWrapper(20584): Caused by: java.lang.NoClassDefFoundError: okhttp3/internal/platform/Platform
E/WM-WorkerWrapper(20584): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
E/WM-WorkerWrapper(20584): 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:955)
E/WM-WorkerWrapper(20584): 	at com.bluechilli.flutteruploader.UploadWorker.doWork(UploadWorker.java:226)
E/WM-WorkerWrapper(20584): 	at androidx.work.Worker$1.run(Worker.java:85)
E/WM-WorkerWrapper(20584): 	... 3 more
I/WM-WorkerWrapper(20584): Worker result FAILURE for Work [ id=6bbb38d3-f97a-4f61-8170-d522d6ddca42, tags={ com.bluechilli.flutteruploader.UploadWorker, flutter_upload_task } ]
I/flutter (20584): 1`

**Comment by ened** [comment]
@conall1995 thx for the report - can you confirm this error is only happening on Android 4.4 ?

**Comment by conall1995** [comment]
> @conall1995 thx for the report - can you confirm this error is only happening on Android 4.4 ?

nope 
i think this exist on android 4.x.x
tested on 4.4.4 and 4.1.x
my code work fine on android 5 and 7 and 8

**Comment by Amospikins** [comment]
I also noticed this too....
didnt work on 4.x.x only from 5
